[platformio]
build_cache_dir = .pio_cache

[env]
lib_ldf_mode = chain+
incremental_build = yes
extra_scripts = pre:ccache.py


[env:loraMeshGasleak1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board1/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak2]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board2-2/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board3/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak4]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board4/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak5]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board5/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak6]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board6/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak7]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board7/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

# [env:loraMeshGasleak8]
# platform = espressif32
# board = esp32-s3-devkitm-1
# framework = arduino
# build_src_filter = +<Gasleak/Board8/>
# build_flags = 
#     -Wno-deprecated-declarations  
# upload_speed = 921600
# upload_port = COM9
# monitor_speed = 115200

[env:loraMeshGasleak9]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board9/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak10]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board10/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGasleak11]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<Gasleak/Board11/>
build_flags = 
    -Wno-deprecated-declarations  
upload_speed = 921600
upload_port = COM9
monitor_speed = 115200

[env:loraMeshGateway]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<loraMeshGateway/>
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 512KB
board_build.filesystem = spiffs
board_build.flash_mode = dout
upload_port = COM10

[env:loraMeshClusterHead]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<loraMeshClusterHead/>
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 512KB
board_build.filesystem = spiffs
board_build.flash_mode = dout
upload_port = COM10

[env:loraMeshClusterHead_ESP32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<loraMeshClusterHead_ESP32/>
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
upload_port = COM10